### ISSUE TITLE
Spec 0.8 document?

### ISSUE THREAD

**Issue by realflight1** [opendroneid/specs#3]
The most recent spec version in this repository is 0.64.3, but the opendroneid-core-c mentions newer versions such as 0.8 and 0.7. The message definitions in the library are indeed a bit different than in spec 0.64.3. Is there an updated spec document for version 0.8? Thanks!

**Comment by friissoren** [comment]
Unfortunately the newer versions of the specification are not publicly available.
The very final editorial changes are currently being done by ASTM and the specification will after that be available for download from the ASTM web-site. I have a feeling that there will be a fee to pay before it is possible to download it though. I am not sure about the details.
Until the spec is available, you can trust that the current implementation of opendroneid-core-c and the example Android receiver implementation are fully compliant with the near-final version.

**Comment by realflight1** [comment]
Thanks for the quick response, I'll close the issue. It might be a good idea to have a note somewhere about ASTM, either in this repo or on opendroneid.org.

**Comment by friissoren** [comment]
Just FYI: The final version of the ASTM document is now available (unfortunately for a fee):
https://www.astm.org/Standards/F3411.htm
